// Cylinder harmonics, exhaust resonance and intake noise: no external audio downloads.
export const ENGINE_PROFILES=[
 {name:'Sport inline-four',cyl:4,idle:900,redline:6800,max:210,tone:1.3,body:.34,intake:.16},
 {name:'Turbo inline-four',cyl:4,idle:850,redline:7400,max:255,tone:1.65,body:.26,intake:.38},
 {name:'Deep V6',cyl:6,idle:700,redline:6000,max:235,tone:.8,body:.56,intake:.12},
 {name:'Cross-plane V8',cyl:8,idle:750,redline:6800,max:295,tone:.68,body:.72,intake:.2},
 {name:'Smooth V12',cyl:12,idle:850,redline:8200,max:330,tone:1.1,body:.22,intake:.23}
];
export function engineState(index,speed,throttle,boost){const p=ENGINE_PROFILES[index]||ENGINE_PROFILES[0],fraction=Math.min(1.12,Math.abs(speed)*3.6/p.max),gear=Math.min(6,1+Math.floor(fraction*5.6)),load=Math.max(0,Math.min(1,throttle));const phase=gear===1?fraction*5.6:(fraction-(gear-1)/5.6)*5.6;const rpm=Math.min(p.redline,Math.max(p.idle,p.idle+(gear===1?phase: .48+phase*.5)*(p.redline-p.idle)+(load*.035+(boost?.05:0))*(p.redline-p.idle)));return {rpm,gear,load,profile:p}}
export class AudioManager{
 constructor(save){this.save=save;this.started=false;this.car=-1;this.gear=1;this.platformMuted=false;this.hiddenMuted=false;const resume=()=>{if(this.started&&this.ctx.state!=='running'&&this.ctx.state!=='closed')this.ctx.resume().catch(()=>{})};for(const name of ['pointerup','touchend','keydown'])document.addEventListener(name,resume,{passive:true});document.addEventListener('visibilitychange',()=>{this.hiddenMuted=document.hidden;this.applyMute()})}
 setPlatformMuted(value){this.platformMuted=!!value;this.applyMute()}
 applyMute(){if(!this.started)return;const g=this.master.gain,t=this.ctx.currentTime;g.cancelScheduledValues(t);g.setValueAtTime(this.platformMuted||this.hiddenMuted?0:this.save.data.settings.master,t)}
 start(){if(this.started){this.ctx.resume().catch(()=>{});return}try{const c=this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=c.createGain();this.master.gain.value=0;this.master.connect(c.destination);this.engineGain=c.createGain();this.engineGain.gain.value=0;this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.filter.Q.value=.7;this.filter.connect(this.engineGain);this.engineGain.connect(this.master);this.exhaust=c.createOscillator();this.exhaust.connect(this.filter);this.exhaust.start();this.body=c.createOscillator();this.body.type='sine';this.bodyGain=c.createGain();this.body.connect(this.bodyGain);this.bodyGain.connect(this.engineGain);this.body.start();const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+(Math.random()*2-1)*.12)/1.12;data[i]=last*3}this.noise=c.createBufferSource();this.noise.buffer=buffer;this.noise.loop=true;this.intakeFilter=c.createBiquadFilter();this.intakeFilter.type='bandpass';this.intakeFilter.Q.value=.6;this.intake=c.createGain();this.intake.gain.value=0;this.noise.connect(this.intakeFilter);this.intakeFilter.connect(this.intake);this.intake.connect(this.master);this.noise.start();this.musicGain=c.createGain();this.musicGain.gain.value=0;this.musicGain.connect(this.master);this.music=c.createOscillator();this.music.connect(this.musicGain);this.music.start();this.started=true;this.select(this.save.data.car);c.resume().catch(()=>{})}catch{this.ctx?.close().catch(()=>{});this.started=false}}
 select(index){if(this.car===index)return;this.car=index;const p=ENGINE_PROFILES[index]||ENGINE_PROFILES[0],real=new Float32Array(25),imag=new Float32Array(25);for(let n=1;n<25;n++){imag[n]=Math.exp(-n/(p.tone*4))/Math.pow(n,.65);if(index===3&&n%2)imag[n]*=1.7;if(index===4&&n%2===0)imag[n]*=.4}this.exhaust.setPeriodicWave(this.ctx.createPeriodicWave(real,imag));this.bodyGain.gain.value=p.body}
 update(speed,active,boost,time,index=this.save.data.car,throttle=0){if(!this.started)return;this.select(index);const s=this.save.data.settings,t=this.ctx.currentTime,e=engineState(index,speed,throttle,boost),p=e.profile;this.gear=e.gear;this.rpm=e.rpm;const set=(param,value,tau=.07)=>param.setTargetAtTime(value,t,tau);set(this.master.gain,this.platformMuted||this.hiddenMuted?0:s.master,.1);set(this.exhaust.frequency,e.rpm/60*p.cyl/2);set(this.body.frequency,e.rpm/120*(index===3?1.01:1));set(this.filter.frequency,180+e.rpm*.17+p.tone*180+e.load*650);set(this.engineGain.gain,active?s.engine*(.11+e.load*.09):0,.1);set(this.intakeFilter.frequency,400+e.rpm*.24);set(this.intake.gain,active?s.engine*p.intake*(.025+e.load*.12+(boost?.04:0)):0,.1);set(this.musicGain.gain,active?s.music*.026:0,.15);set(this.music.frequency,[110,130.81,164.81,146.83,110,164.81,130.81,98][Math.floor(time*2)%8],.1)}
 tone(freq=600,duration=.1,type='sine'){if(!this.started)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(this.save.data.settings.effects*.12,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.onended=()=>{o.disconnect();g.disconnect()};o.start();o.stop(t+duration)}
}
