import {platform,FixedStepper} from './platform.js';
import {World,T} from './world.js';
import {CARS,MAPS,MAP_PRICES,ownsMap,purchaseMap,formatNumber,formatDistance,awardDistanceCoins,DEFAULT_KEYS,SaveManager,InputManager,VehiclePhysics,AudioManager} from './systems.js';
import {Progression,ACHIEVEMENTS} from './progression.js';
import {GarageView} from './garage-view.js';
import {ENGINE_PROFILES} from './engine-audio.js';
import {TrafficManager} from './traffic.js';
const $=id=>document.getElementById(id),save=new SaveManager(),audio=new AudioManager(save),physics=new VehiclePhysics();const progression=new Progression(save);let world,garageView,audioThrottle=0,achievementTimer=0;
platform.onMute=value=>audio.setPlatformMuted(value);
try{world=new World($('world'))}catch(e){$('error').hidden=false;throw e}
world.quality(save.data.settings.quality);world.setCar(CARS[save.data.car].type,save.data.paint);const traffic=new TrafficManager(world);
let state='menu',panelKind='',returnState='menu',cameraMode=0,headlights=false,run,previewCar=save.data.car,count=0,feedbackTimer=0,shake=0,last=performance.now(),time=0,menuDistance=110,runSaved=false;
function setState(next){state=next;platform.setGameplay(next==='playing')}
platform.getState=()=>state;
const cameraNames=['CHASE CAM','CLOSE CHASE','HOOD CAM','CINEMATIC'];
const input=new InputManager(save.data.keys,action,()=>state==='playing'||state==='countdown'||(state==='paused'&&panelKind==='pause'));
function freshRun(){return {score:0,distance:0,coins:0,topSpeed:0,near:0,overtakes:0,combo:1,comboTimer:0,chain:0,milestonesPaid:0}}
run=freshRun();
function action(a){if(a==='blur'){simulation.reset();last=performance.now();if(state==='playing'||state==='countdown')pause();return}if(a==='pause'){if($('panel').open){if(panelKind==='pause')closePanel();return}if(state==='playing'||state==='countdown')pause();return}if(state!=='playing')return;if(a==='camera')cameraMode=(cameraMode+1)%4;if(a==='horn')audio.tone(165,.4,'sawtooth');if(a==='lights')headlights=!headlights;}

function customize(){world.player.userData.paint.color.set(save.data.paint);world.player.userData.glass.color.set('#5a7680').multiplyScalar(1-save.data.tint*.8);for(let w of world.player.userData.wheels)w.hub.material.color.set(save.data.wheel==='Black'?'#22282b':'#9da8ab')}
function updateMenu(){updateMapPicker();const c=CARS[save.data.car];$('bestMenu').textContent=formatNumber(save.data.best);$('coinsMenu').textContent=formatNumber(save.data.coins);$('selectedName').textContent=`0${save.data.car+1} / ${c.name.toUpperCase()}`;$('carDescription').textContent=c.desc;$('menuTopSpeed').textContent=c.speed;customize()}
function screen(mode){const menu=mode==='menu';$('menuLayout').hidden=!menu;if(menu)world.camera.setViewOffset(innerWidth,innerHeight,-innerWidth*.18,0,innerWidth,innerHeight);else world.camera.clearViewOffset();$('menu').hidden=!menu;$('menuFooter').hidden=!menu;$('carLabel').hidden=!menu;$('hud').hidden=menu;$('pauseButton').hidden=menu;$('touch').hidden=menu||!(matchMedia('(pointer:coarse)').matches||innerWidth<900);document.body.classList.toggle('driving',!menu)}
function start(){if(platform.adPending)return;if(!ownsMap(save.data,save.data.settings.map)){if($('panel').open)$('panel').close();setState('menu');screen('menu');updateMenu();return}if($('panel').open)$('panel').close();input.clear();world.setCar(CARS[save.data.car].type,save.data.paint);customize();physics.reset();run=freshRun();runSaved=false;traffic.reset();setState('countdown');count=3.2;screen('playing');$('countdown').hidden=false;$('countdown').textContent='3';audio.start();$('bestHud').textContent='BEST '+formatNumber(save.data.best);document.activeElement?.blur();for(let i=0;i<5;i++)traffic.spawn(0);cameraMode=0;feedbackTimer=0;message('');world.camera.position.set(1.75,4.6,10);world.camera.lookAt(1.75,.8,-22)}
function bank(){if(runSaved)return;save.data.best=Math.max(save.data.best,Math.floor(run.score));save.data.coins+=run.coins;progression.flush();runSaved=true}
function home(){if(platform.adPending)return;bank();if($('panel').open)$('panel').close();setState('menu');input.clear();screen('menu');$('countdown').hidden=true;traffic.reset();world.setCar(CARS[save.data.car].type,save.data.paint);updateMenu()}
function openPanel(kind){if(platform.adPending)return;progression.flush();input.clear();panelKind=kind;returnState=state;if(state==='playing'||state==='countdown')setState('paused');renderPanel();if(!$('panel').open)$('panel').showModal()}
function closePanel(){if(platform.adPending)return;input.binding=null;if(panelKind==='pause'){setState(pausedFrom==='countdown'?'countdown':'playing')}else if(panelKind==='settings'&&(returnState==='paused'||returnState==='playing'||returnState==='countdown')){panelKind='pause';renderPanel();return}else if(panelKind==='results'){home();return}else if(state==='paused'){setState(returnState)}if(panelKind==='garage'){world.setCar(CARS[save.data.car].type,save.data.paint);updateMenu()}$('panel').close();input.clear()}
let pausedFrom='playing';function pause(){if(state!=='playing'&&state!=='countdown')return;pausedFrom=state;openPanel('pause')}
function message(text){$('feedback').textContent=text;feedbackTimer=text?2:0;$('feedback').style.opacity=text?1:0}
function event(type,severity){if(type==='health'){progression.stats.healthPacks++;audio.tone(740,.22);message(severity>0?`+${formatNumber(severity)} HEALTH`:'HEALTH FULL');return}if(type==='collision'){progression.stats.collisions++;run.combo=1;run.chain=0;run.comboTimer=0;shake=.5;audio.tone(65,.35,'sawtooth');message(severity>35?'HEAVY IMPACT':'CONTACT · KEEP GOING');if(physics.health<=0)endRun();return}if(type==='coin'){run.coins+=10;progression.earn(10);physics.nitro=Math.min(100,physics.nitro+7);run.score+=50*run.combo;audio.tone(990,.12);message('+10 COINS');return}run.overtakes++;progression.stats.overtakes++;run.chain++;run.combo=Math.min(8,1+Math.floor(run.chain/3));run.comboTimer=6;const near=type==='near'||type==='extreme';if(near){run.near++;physics.nitro=Math.min(100,physics.nitro+(type==='extreme'?20:12));const reward=type==='extreme'?20:10;run.coins+=reward;progression.earn(reward);progression.stats.near++}const points=(type==='extreme'?500:type==='near'?250:physics.speed>45?150:75)*run.combo;run.score+=points;audio.tone(near?820:520,.09);if(near){message(`${type==='extreme'?'EXTREME NEAR MISS +20':'NEAR MISS +10'} COINS`);return}message(`${type==='extreme'?'EXTREME NEAR MISS':near?'NEAR MISS':physics.speed>45?'FAST OVERTAKE':'OVERTAKE'}  +${formatNumber(points)}`)}
function endRun(){if(state==='over')return;setState('over');progression.stats.crashes++;const newBest=run.score>save.data.best;bank();input.clear();$('countdown').hidden=true;panelKind='results';returnState='over';run.newBest=newBest;renderPanel();$('panel').showModal()}
function bind(id,fn){$(id)?.addEventListener('click',fn)}
function renderPanel(){$('panel').dataset.kind=panelKind;const p=$('panelContent');$('panelKicker').textContent=panelKind==='garage'?`YOUR GARAGE · ◈ ${formatNumber(save.data.coins)} COINS`:'OUT OFFICE';
 if(panelKind==='pause'){p.innerHTML='<h2>TAKE A BREATHER.</h2><p>The road will wait for you.</p><div class="dialog-actions"><button id="resume" class="primary">RESUME DRIVE <span>↗</span></button><button id="restart" class="plain">RESTART</button></div><div class="secondary-actions"><button id="pauseSettings">SETTINGS</button><button id="pauseHome">MAIN MENU</button></div>';bind('resume',closePanel);bind('restart',()=>{bank();start()});bind('pauseSettings',()=>{panelKind='settings';returnState='paused';renderPanel()});bind('pauseHome',home)}
 else if(panelKind==='results'){p.innerHTML=`<h2>${run.newBest?'A NEW PERSONAL BEST.':'RUN OVER.'}</h2><p>There’s always another road. Make the next run count.</p><div class="big-score">${formatNumber(run.score)}</div><small>RUN SCORE · BEST ${formatNumber(save.data.best)}</small><div class="result-grid"><div><small>DISTANCE</small><b>${formatDistance(run.distance/1000)} km</b></div><div><small>TOP SPEED</small><b>${Math.round(run.topSpeed)} km/h</b></div><div><small>COINS EARNED</small><b class="gold">◈ ${formatNumber(run.coins)}</b></div><div><small>NEAR MISSES</small><b>${formatNumber(run.near)}</b></div><div><small>OVERTAKES</small><b>${formatNumber(run.overtakes)}</b></div><div><small>BEST SCORE</small><b>${formatNumber(save.data.best)}</b></div></div><div class="dialog-actions"><button class="primary" id="retry">DRIVE AGAIN <span>↗</span></button><button class="plain" id="resultGarage">GARAGE</button><button class="plain" id="resultHome">MAIN MENU</button></div>`;bind('retry',start);bind('resultHome',home);bind('resultGarage',()=>{home();previewCar=save.data.car;openPanel('garage')})}
 else if(panelKind==='help'){p.innerHTML='<h2>OWN THE OPEN ROAD.</h2><p>Hold the throttle, pick your line, and pass traffic cleanly. Close passes build your multiplier and refill nitro. Heavy impacts end your run when health reaches zero.</p><div class="key-grid">'+Object.entries({throttle:'Accelerate',brake:'Brake / reverse',left:'Steer left',right:'Steer right',nitro:'Nitro boost',handbrake:'Handbrake',camera:'Change camera',horn:'Horn',lights:'Headlights'}).map(([k,v])=>`<div>${v}<kbd>${keyLabel(save.data.keys[k])}</kbd></div>`).join('')+'<div>Pause / resume<kbd>SPACE</kbd></div></div><p>Arrow keys also work. On mobile, hold the on-screen controls. Gamepad: left stick to steer, triggers for throttle/brake, A for nitro, Y for camera and Start to pause.</p><button class="primary" id="helpDrive">LET’S DRIVE <span>↗</span></button>';bind('helpDrive',start)}
 else if(panelKind==='about'){p.innerHTML='<h2>ABOUT OUT OFFICE</h2><p>Leave the everyday behind and find your rhythm on the open road. Out Office is an endless arcade driving game about speed, precision, and beating your personal best.</p><p>Explore three free maps: Pacific Coast, Greenwood Forest, and Metro City. Preview Alpine Pass and Neon Harbour, then unlock them with earned coins to drive there. Collect glowing + pickups to restore 25 health when you’re running low. Overtake traffic, collect coins, and earn 50 coins for every 2 km you drive. Close passes refill nitro and build your score multiplier.</p><p>Use your coins to unlock five vehicles and customize your ride. Your scores, coins, vehicles, and preferences are saved in this browser.</p><button class="primary" id="aboutDone">BACK TO MENU <span>↗</span></button>';bind('aboutDone',closePanel)}
 else if(panelKind==='achievements')renderAchievements(p);
 else if(panelKind==='statistics')renderStatistics(p);
 else if(panelKind==='garage')renderGarage(p);
 else if(panelKind==='settings')renderSettings(p);
}
function keyLabel(k){return k.replace('Key','').replace('Digit','').replace('Arrow','').replace('Left','').replace('Right','')}
function renderGarage(p){const c=CARS[previewCar],owned=save.data.unlocked.includes(previewCar);p.innerHTML=`<h2>SELECT VEHICLE</h2><div class="garage-grid">${CARS.map((c,i)=>`<button data-car="${i}" class="vehicle-card ${i===previewCar?'selected':''}"><small>0${i+1} / ${i===save.data.car?'SELECTED':save.data.unlocked.includes(i)?'OWNED':'LOCKED'}</small><b>${c.name}</b><span>${save.data.unlocked.includes(i)?i===save.data.car?'SELECTED':'SELECT':'◈ '+formatNumber(c.price)}</span></button>`).join('')}</div><div class="garage-preview" id="garagePreview"></div><div class="inspection-controls"><span>DRAG TO ROTATE · ${ENGINE_PROFILES[previewCar].name.toUpperCase()}</span><div>${[['front','Front'],['side','Side'],['rear','Rear'],['in','Zoom +'],['out','Zoom −'],['reset','Reset view']].map(([view,label])=>`<button class="plain" data-view="${view}">${label}</button>`).join('')}</div></div><div class="garage-details"><div><h2>${c.name.toUpperCase()}</h2><p>${c.desc}</p>${[['TOP SPEED',c.speed/350,`${c.speed} km/h`],['ACCELERATION',c.accel/17,''],['HANDLING',c.handling/1.3,''],['BRAKING',c.brake/35,''],['NITRO',c.nitro/1.5,'']].map(([n,v,t])=>`<div class="stat">${n} ${t}<span><i style="width:${v*100}%"></i></span></div>`).join('')}</div><div><small>BODY PAINT</small><div class="swatches">${['#edb03a','#c13c30','#c5d0cb','#294e65','#252a2f','#738770'].map(color=>`<button aria-label="Paint ${color}" data-color="${color}" class="swatch ${color===save.data.paint?'selected':''}" style="background:${color}"></button>`).join('')}</div><label class="setting-row">Wheel finish<select id="wheel"><option>Alloy</option><option>Black</option></select></label><label class="setting-row">Window tint<input id="tint" type="range" min="0" max=".9" step=".1" value="${save.data.tint}"></label><p>Earn coins from pickups, close passes, and distance challenges.</p></div></div><div class="dialog-actions"><button class="primary" id="selectCar" ${!owned&&save.data.coins<c.price?'disabled':''}>${owned?previewCar===save.data.car?'SELECTED':'SELECT':'UNLOCK FOR ◈ '+formatNumber(c.price)}<span>↗</span></button><button class="plain" id="garageDone">DONE</button></div>`;
 garageView??=new GarageView();const inspect=()=>garageView.attach($('garagePreview'),c.type,save.data.paint,save.data.tint,save.data.wheel);inspect();for(const b of p.querySelectorAll('[data-view]'))b.onclick=()=>garageView.view(b.dataset.view);
 for(let b of p.querySelectorAll('[data-car]'))b.onclick=()=>{previewCar=+b.dataset.car;if(save.data.unlocked.includes(previewCar)){save.data.car=previewCar;save.save();updateMenu()}world.setCar(CARS[previewCar].type,save.data.paint);customize();renderGarage(p)};
 for(let b of p.querySelectorAll('[data-color]'))b.onclick=()=>{save.data.paint=b.dataset.color;save.save();customize();renderGarage(p)};
 $('wheel').value=save.data.wheel;$('wheel').onchange=e=>{save.data.wheel=e.target.value;save.save();customize();inspect()};$('tint').oninput=e=>{save.data.tint=+e.target.value;save.save();customize();inspect()};bind('selectCar',()=>{if(!owned){if(save.data.coins<c.price)return;save.data.coins-=c.price;save.data.unlocked.push(previewCar);progression.flush()}save.data.car=previewCar;save.save();updateMenu();$('panelKicker').textContent=`YOUR GARAGE · ◈ ${formatNumber(save.data.coins)} COINS`;renderGarage(p)});bind('garageDone',closePanel)
}

function renderAchievements(p){const count=ACHIEVEMENTS.filter(a=>save.data.achievements[a.id]).length;p.innerHTML=`<h2>EVERY MILE COUNTS.</h2><p>${count} of ${ACHIEVEMENTS.length} achievements unlocked. Keep driving to build your collection.</p><div class="achievement-grid">${ACHIEVEMENTS.map(a=>{const unlocked=save.data.achievements[a.id],value=Math.min(a.target,progression.metric(a.metric));return `<article class="achievement-card ${unlocked?'earned':''}"><small>${unlocked?'✓ UNLOCKED':'IN PROGRESS'}</small><h3>${a.title}</h3><p>${a.description}</p><progress max="${a.target}" value="${value}" aria-label="${a.title}"></progress><span>${formatNumber(value)} / ${formatNumber(a.target)}${['longestRun','distance'].includes(a.metric)?' m':''}</span></article>`}).join('')}</div><button class="primary" id="progressDone">DONE <span>↗</span></button>`;bind('progressDone',closePanel)}
function renderStatistics(p){const st=progression.stats,car=progression.favourite('carDistance'),map=progression.favourite('mapDistance');const metrics=[['TOTAL DISTANCE',formatDistance(st.distance/1000)+' km'],['COINS COLLECTED',formatNumber(st.coins)],['LONGEST RUN',formatDistance(st.longestRun/1000)+' km'],['RUNS STARTED',formatNumber(st.runs)],['CRASHES · RUNS ENDED',formatNumber(st.crashes)],['TRAFFIC COLLISIONS',formatNumber(st.collisions)],['HEALTH PACKS',formatNumber(st.healthPacks)],['NEAR MISSES',formatNumber(st.near)],['OVERTAKES',formatNumber(st.overtakes)],['TOP SPEED',formatNumber(st.topSpeed)+' km/h'],['FAVOURITE CAR',car===null?'Start driving':CARS[car]?.name||'—'],['FAVOURITE MAP',map===null?'Start driving':MAPS[map]||'—']];p.innerHTML=`<h2>YOUR ROAD RECORD.</h2><p>Every escape adds up. Favourites are based on distance driven.</p><div class="lifetime-grid">${metrics.map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('')}</div><p class="tracking-note">Tracking since ${new Date(st.since).toLocaleDateString()}. Coins include pickups, near misses and distance rewards, even after you spend them. Earlier driving history is unavailable. Saved in this browser.</p><button class="primary" id="statsDone">DONE <span>↗</span></button>`;bind('statsDone',closePanel)}

function renderSettings(p){const s=save.data.settings;p.innerHTML=`<h2>MAKE IT YOURS.</h2><div class="settings-columns"><div><h3>DRIVING & DISPLAY</h3><label class="setting-row">Graphics<select id="quality">${['Low','Medium','High','Ultra'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="setting-row">Environment<select id="weather">${['Sunset','Night','Fog','Rain','Cycle'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="setting-row">Speed unit<select id="unitSetting"><option>km/h</option><option>mph</option></select></label><label class="setting-row">Steering sensitivity<input data-setting="sensitivity" type="range" min=".5" max="1.5" step=".05" value="${s.sensitivity}"></label><label class="setting-row">Motion effects<input data-setting="motion" type="checkbox" ${s.motion?'checked':''}></label><label class="setting-row">Automatic throttle<input data-setting="auto" type="checkbox" ${s.auto?'checked':''}></label></div><div><h3>AUDIO</h3>${['master','music','engine','effects'].map(n=>`<label class="setting-row">${n[0].toUpperCase()+n.slice(1)}<input data-setting="${n}" type="range" min="0" max="1" step=".05" value="${s[n]}"></label>`).join('')}<h3>KEY BINDINGS</h3><small>SELECT A KEY TO REBIND · SPACE PAUSES</small><div class="key-grid">${Object.entries(save.data.keys).map(([n,k])=>`<div>${n[0].toUpperCase()+n.slice(1)}<button data-key="${n}">${keyLabel(k)}</button></div>`).join('')}</div></div></div><div class="dialog-actions"><button class="primary" id="settingsDone">SAVE & RETURN <span>↗</span></button><button class="plain" id="resetKeys">RESET KEYS</button></div>`;
 for(const n of ['quality','weather']){$(n).value=s[n];$(n).onchange=e=>{s[n]=e.target.value;if(n==='quality')world.quality(s.quality);save.save()}}$('unitSetting').value=s.unit;$('unitSetting').onchange=e=>{s.unit=e.target.value;save.save()};for(let el of p.querySelectorAll('[data-setting]'))el.oninput=()=>{s[el.dataset.setting]=el.type==='checkbox'?el.checked:+el.value;save.save()};for(let b of p.querySelectorAll('[data-key]'))b.onclick=()=>{b.textContent='…';input.binding=code=>{const name=b.dataset.key,other=Object.entries(save.data.keys).find(([n,k])=>k===code&&n!==name);if(other)save.data.keys[other[0]]=save.data.keys[name];save.data.keys[name]=code;input.keys=save.data.keys;save.save();renderSettings(p)}};bind('resetKeys',()=>{save.data.keys={...DEFAULT_KEYS};input.keys=save.data.keys;save.save();renderSettings(p)});bind('settingsDone',closePanel)
}
const mapDescriptions={coast:'Pacific Coast · Open water & sunset skies',forest:'Greenwood Forest · A route through the pines',city:'Metro City · Skylines & city lights',alpine:'Alpine Pass · Snow-capped peaks & frosted pines',harbour:'Neon Harbour · Illuminated skyline & waterfront docks'};
function updateMapPicker(){
 const id=save.data.settings.map,owned=ownsMap(save.data,id),price=MAP_PRICES[id];
 for(const radio of document.querySelectorAll('input[name="map"]'))radio.checked=radio.value===id;
 $('mapDescription').textContent=mapDescriptions[id];
 for(const premium of ['alpine','harbour'])$(premium+'Status').textContent=ownsMap(save.data,premium)?'OWNED':formatNumber(MAP_PRICES[premium])+' COINS';
 $('playButton').disabled=!owned;$('playButton').innerHTML=owned?'PLAY NOW <span>↗</span>':'MAP LOCKED <span aria-hidden="true">⊘</span>';
 $('purchaseMap').hidden=owned;$('purchaseMap').disabled=save.data.coins<price;$('purchaseMap').textContent='UNLOCK · '+formatNumber(price)+' COINS';
 $('mapStatus').textContent=owned?(price?'OWNED · Ready to drive':''):('PREVIEW · '+(save.data.coins<price?'Earn '+formatNumber(price-save.data.coins)+' more coins to unlock.':'Unlock this map to drive.'));
}
bind('purchaseMap',()=>{if(state!=='menu')return;const result=purchaseMap(save.data,save.data.settings.map);if(!result.ok){updateMapPicker();return}progression.flush();updateMenu();audio.tone(880,.18);$('mapStatus').textContent='UNLOCKED · Ready to drive'});

for(const radio of document.querySelectorAll('input[name="map"]'))radio.onchange=()=>{if(state!=='menu'||!radio.checked)return;save.data.settings.map=radio.value;save.save();updateMapPicker()};
bind('achievementsButton',()=>openPanel('achievements'));bind('statisticsButton',()=>openPanel('statistics'));
$('copyrightYear').textContent=new Date().getFullYear();bind('aboutButton',()=>openPanel('about'));bind('playButton',start);bind('garageButton',()=>{previewCar=save.data.car;openPanel('garage')});bind('settingsButton',()=>openPanel('settings'));bind('helpButton',()=>openPanel('help'));bind('closePanel',closePanel);bind('pauseButton',pause);bind('touchCamera',()=>action('camera'));for(const type of ['contextmenu','selectstart','dragstart'])$('touch').addEventListener(type,e=>e.preventDefault());bind('soundButton',()=>{audio.start();save.data.settings.master=save.data.settings.master>0?0:.65;save.save();$('soundButton').textContent=save.data.settings.master?'♪':'♩';$('soundButton').ariaLabel=save.data.settings.master?'Mute sound':'Enable sound'});document.querySelector('.brand').onclick=e=>{e.preventDefault();if(state==='playing'||state==='countdown')pause();else if(state==='menu')home()};$('panel').addEventListener('cancel',e=>{e.preventDefault();closePanel()});
$('world').addEventListener('wheel',e=>e.preventDefault(),{passive:false});
$('hud').addEventListener('wheel',e=>{if(state==='playing'||state==='countdown')e.preventDefault()},{passive:false});
$('touch').addEventListener('wheel',e=>e.preventDefault(),{passive:false});
let hudElapsed=1;
function updateHUD(){let kmh=Math.abs(physics.speed)*3.6;$('score').textContent=formatNumber(run.score);$('distance').innerHTML=formatDistance(run.distance/1000)+' <small>KM</small>';$('coins').textContent='◈ '+formatNumber(run.coins);$('speed').textContent=Math.round(kmh*(save.data.settings.unit==='mph'?.621371:1));$('unit').textContent=save.data.settings.unit.toUpperCase();$('gear').textContent=physics.speed<0?'R':kmh<2?'N':audio.gear||1;$('cameraName').textContent=cameraNames[cameraMode];$('rpm').style.width=Math.min(100,(audio.rpm||900)/ENGINE_PROFILES[save.data.car].redline*100)+'%';$('nitro').style.width=physics.nitro+'%';$('health').style.width=physics.health+'%';$('health').style.background=physics.health<35?'#f27252':'#dbe4dc';$('combo').textContent='×'+run.combo;$('comboTime').style.width=run.comboTimer/6*100+'%';$('challenge').innerHTML=`DISTANCE REWARD <b>Reach ${formatNumber((run.milestonesPaid+1)*2)} km · +50 coins</b>`}
const targetPos=new T.Vector3(),look=new T.Vector3();
const simulation=new FixedStepper(1/60);let lastControls={brake:0,handbrake:false};
function simulate(dt){if(platform.adPending||document.hidden)return; if(state==='countdown'){count-=dt;let n=Math.ceil(count);$('countdown').textContent=n>0?n:'GO';if(count<-.45){setState('playing');$('countdown').hidden=true;message('THE ROAD IS YOURS')}}
 if(state==='playing'){const controls=input.read();if(state!=='playing')return;lastControls=controls;audioThrottle=save.data.settings.auto?1:controls.throttle;const travelled=physics.update(dt,controls,CARS[save.data.car],save.data.settings);run.distance+=travelled;run.score+=travelled*(1+physics.speed/60)*run.combo;run.topSpeed=Math.max(run.topSpeed,physics.speed*3.6);run.comboTimer=Math.max(0,run.comboTimer-dt);if(run.comboTimer===0){run.combo=1;run.chain=0}const distanceAward=awardDistanceCoins(run);if(distanceAward){progression.earn(distanceAward);message(`${formatNumber(run.milestonesPaid*2)} KM MILESTONE · +${formatNumber(distanceAward)} COINS`);audio.tone(1040,.3)}progression.drive(dt,travelled,run,save.data.car,save.data.settings.map);traffic.update(dt,run,physics,event);progression.stats.maxCombo=Math.max(progression.stats.maxCombo,run.combo);

 }
}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;if(document.hidden)return;time+=dt;
 simulation.advance(dt,simulate);const playing=state==='playing',menu=state==='menu';
 if(playing){const controls=lastControls;
 world.player.position.set(physics.x,Math.sin(time*20)*Math.min(.01,physics.speed*.0002),0);world.player.rotation.y=physics.yaw;world.player.userData.body.rotation.z=physics.steer*Math.min(.055,physics.speed*.001);world.player.userData.body.rotation.x=physics.acceleration*.002;for(let w of world.player.userData.wheels){w.pivot.rotation.y=w.front?physics.yaw*1.7:0;w.wheel.rotation.x-=physics.speed*dt/.39;w.hub.rotation.x=w.wheel.rotation.x}world.player.userData.tail.emissiveIntensity=controls.brake||controls.handbrake?5:.8;
 }
 if(menu){menuDistance+=dt*1.3;world.player.position.set(1.75,Math.sin(time*2)*.006,0);world.player.rotation.y=-.14;world.player.userData.body.rotation.set(0,0,0);targetPos.set(-6.5,3.1,8.8);look.set(1.3,.7,-.2)}else{const x=physics.x;switch(cameraMode){case 0:targetPos.set(x*.78,4.2,9.8+physics.speed*.025);look.set(x*.8,1,-22);break;case 1:targetPos.set(x*.9,2.4,6.5);look.set(x*.9,.9,-24);break;case 2:targetPos.set(x,1.26,-1.5);look.set(x-Math.sin(physics.yaw)*20,1.2,-40);break;default:targetPos.set(x-6,5.4,10);look.set(x,1,-15)}if(shake>0&&save.data.settings.motion){targetPos.x+=(Math.random()-.5)*shake;targetPos.y+=(Math.random()-.5)*shake}}
 world.player.visible=cameraMode!==2||menu;const lights=headlights||world.night>.35;for(let l of world.player.userData.beams)l.intensity=lights?45:0;world.player.userData.light.emissiveIntensity=lights?4:1.5;
 const active=playing||state==='countdown';world.update(menu?menuDistance:run.distance,menu||active?dt:0,save.data.settings.map,save.data.settings.weather);
 if(active||menu){world.camera.position.lerp(targetPos,1-Math.exp(-dt*(menu?2:7)));world.camera.lookAt(look);const fov=menu?49:cameraMode===2?70:55+(save.data.settings.motion?physics.speed*.12+(physics.boost?6:0):0);world.camera.fov+=(fov-world.camera.fov)*dt*3;world.camera.updateProjectionMatrix()}
 shake=Math.max(0,shake-dt);$('flash').style.opacity=shake*.35;if(feedbackTimer>0&&active){feedbackTimer-=dt;$('feedback').style.opacity=Math.min(1,feedbackTimer*2)}const boosting=playing&&physics.boost;document.body.classList.toggle('boosting',boosting);$('boostBadge').hidden=!boosting;for(const flame of world.player.userData.flames){flame.visible=boosting;flame.scale.y=boosting?1.1+Math.sin(time*44)*.2:1;}document.body.classList.toggle('reduce-motion',!save.data.settings.motion);audio.update(Math.max(0,physics.speed),state==='playing',physics.boost,time,save.data.car,audioThrottle);hudElapsed+=dt;if(!menu&&hudElapsed>=.05){updateHUD();hudElapsed=0}$('zoneLabel').textContent=MAPS[save.data.settings.map].toUpperCase()+' / '+(state==='menu'&&!ownsMap(save.data,save.data.settings.map)?'PREVIEW':save.data.settings.map==='harbour'?'NIGHT RUN':save.data.settings.weather.toUpperCase()+' RUN');world.render();if($('panel').open&&panelKind==='garage')garageView?.render();achievementTimer=Math.max(0,achievementTimer-dt);if(!achievementTimer&&progression.pending.length){$('achievementToast').textContent='ACHIEVEMENT UNLOCKED · '+progression.pending.shift();$('achievementToast').hidden=false;achievementTimer=4}else if(!achievementTimer)$('achievementToast').hidden=true;
}
addEventListener('pagehide',()=>{progression.flush()});
document.addEventListener('visibilitychange',()=>{if(document.hidden)progression.flush()});
addEventListener('resize',()=>{if(state==='menu')world.camera.setViewOffset(innerWidth,innerHeight,-innerWidth*.18,0,innerWidth,innerHeight);else $('touch').hidden=!(matchMedia('(pointer:coarse)').matches||innerWidth<900)});
const desktopMap=matchMedia('(min-width:760px)');function placeMapPicker(){(desktopMap.matches?$('menuRight'):$('mapSlot')).appendChild($('mapPicker'))}desktopMap.addEventListener('change',placeMapPicker);placeMapPicker();
const mapLayoutObserver=new ResizeObserver(()=>{const height=innerWidth>=760?Math.max(0,$('menuRight').offsetTop+$('menuRight').offsetHeight-parseFloat(getComputedStyle($('menuLayout')).paddingTop)+24):0;$('menuLayout').style.setProperty('--map-menu-height',height+'px')});mapLayoutObserver.observe($('menuRight'));
updateMenu();screen('menu');world.camera.position.set(-6.5,3.1,8.8);world.camera.lookAt(1.3,.7,-.2);world.update(menuDistance,0,save.data.settings.map,save.data.settings.weather);world.render();$('loading').hidden=true;platform.setLoading(false);last=performance.now();requestAnimationFrame(frame);
// Expose the same session actions to browsers that support WebMCP.
if(document.modelContext?.registerTool){for(const tool of [{name:'read_drive_status',description:'Read current driving session and saved progression.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,score:Math.floor(run.score),distanceKm:run.distance/1000,vehicle:CARS[save.data.car].name,map:MAPS[save.data.settings.map],best:save.data.best,coins:save.data.coins})},{name:'pause_drive',description:'Pause an active driving session.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(state!=='playing'&&state!=='countdown')throw new Error('No active drive');pause();return {state}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
